### PR TITLE
Improve coverage of lexer

### PR DESCRIPTION
**Pull request by pyrmont**
Hi :) I've joined the Rouge project as one of its maintainers and am helping clear through the backlog of PRs.

I made some changes to your Brainfuck lexer to improve its coverage of valid syntax (based on [the Wikipedia article](https://en.wikipedia.org/wiki/Brainfuck)). 

Let me know if any of it is unclear!

### CODE REVIEW

**Comment by pyrmont** [comment]
Strictly speaking, I think multiline comments can occur anywhere as long as the loop counter is zero but since maintaining accurate counts would be a nightmare—and on the assumption that the primary location for multiline comments is the start of the file—I've taken that route instead.

**Comment by pyrmont** [comment]
Ah, and sorry for all the changes. I rebased against master. We've changed the Gemfile and Travis configuration since your submission and it won't pass the CI tests otherwise.

**Comment by espositoandrea** [comment]
> Strictly speaking, I think multiline comments can occur anywhere as long as the loop counter is zero but since maintaining accurate counts would be a nightmare—and on the assumption that the primary location for multiline comments is the start of the file—I've taken that route instead.

@pyrmont Actually, that is not a bad assumption: the BrainF\*ck language does not have a 'real' syntax for comments: every character that is not a command is treated as a comment. It's just _"common"_ (yeah I know: common and BrainF\*ck can sound like two opposite words) to put a starting comment explaining the program at its beginning.

**Comment by pyrmont** [comment]
@espositoandrea Yeah, that's what it seemed like from the Wikipedia article :)

**Pull request merged**
